export interface Question{
    id?:number,
    question?:string,
    option1?:string,
    option2?:string,
    option3?:string,
    option4?:string,
    answer?:string,
    correct1?:boolean,
    correct2?:boolean,
    correct3?:boolean,
    correct4?:boolean,
    selected?:string,
    select1?:boolean,
    select2?:boolean,
    select3?:boolean,
    select4?:boolean,
    num?:number
}